2025-05-10 06:25:41|ERROR   |root                            |BAZARR cannot bind to specified IP, trying with ***.***.***.***|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server\n    self.server = create_server(app,\n                  ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server\n    last_serv = TcpWSGIServer(\n                ^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__\n    self.bind_server_socket()\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket\n    self.bind(sockaddr)\n  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind\n    return self.socket.bind(addr)\n           ^^^^^^^^^^^^^^^^^^^^^^\nOSError: [Errno 99] Address not available'|
2025-05-10 06:25:42|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-05-10 06:25:42|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-05-10 06:25:42|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-05-10 06:25:43|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-05-10 06:25:43|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-05-10 11:12:37|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-10 11:51:19|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-05-10 13:24:20|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 13:39:01 -04)" was missed by 0:00:18.401549|
2025-05-10 13:39:25|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 13:54:01 -04)" was missed by 0:00:23.555744|
2025-05-10 13:54:31|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 14:09:01 -04)" was missed by 0:00:29.257702|
2025-05-10 14:09:30|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 14:24:01 -04)" was missed by 0:00:28.883851|
2025-05-10 14:24:25|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 14:39:01 -04)" was missed by 0:00:24.194023|
2025-05-10 14:39:34|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 14:54:01 -04)" was missed by 0:00:32.401945|
2025-05-10 14:46:17|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-05-10 14:46:22|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-05-10 14:46:47|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-05-10 14:46:47|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-05-10 14:54:20|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 15:09:01 -04)" was missed by 0:00:18.290713|
2025-05-10 14:59:14|ERROR   |root                            |BAZARR cannot bind to specified IP, trying with ***.***.***.***|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server\n    self.server = create_server(app,\n                  ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server\n    last_serv = TcpWSGIServer(\n                ^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__\n    self.bind_server_socket()\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket\n    self.bind(sockaddr)\n  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind\n    return self.socket.bind(addr)\n           ^^^^^^^^^^^^^^^^^^^^^^\nOSError: [Errno 99] Address not available'|
2025-05-10 14:59:16|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-05-10 14:59:16|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-05-10 14:59:16|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-05-10 14:59:16|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-05-10 14:59:16|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-05-10 15:00:28|ERROR   |root                            |BAZARR cannot bind to specified IP, trying with ***.***.***.***|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server\n    self.server = create_server(app,\n                  ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server\n    last_serv = TcpWSGIServer(\n                ^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__\n    self.bind_server_socket()\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket\n    self.bind(sockaddr)\n  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind\n    return self.socket.bind(addr)\n           ^^^^^^^^^^^^^^^^^^^^^^\nOSError: [Errno 99] Address not available'|
2025-05-10 15:00:29|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-05-10 15:00:29|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-05-10 15:00:29|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-05-10 15:00:29|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-05-10 15:00:29|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-05-10 15:14:41|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 15:29:03 -04)" was missed by 0:00:38.142117|
2025-05-10 15:28:30|ERROR   |root                            |BAZARR cannot bind to specified IP, trying with ***.***.***.***|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server\n    self.server = create_server(app,\n                  ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server\n    last_serv = TcpWSGIServer(\n                ^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__\n    self.bind_server_socket()\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket\n    self.bind(sockaddr)\n  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind\n    return self.socket.bind(addr)\n           ^^^^^^^^^^^^^^^^^^^^^^\nOSError: [Errno 99] Address not available'|
2025-05-10 15:28:31|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-05-10 15:28:31|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-05-10 15:28:31|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-05-10 15:28:31|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-05-10 15:28:31|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-05-10 15:40:24|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 15:54:50 -04)" was missed by 0:00:34.674185|
2025-05-10 15:55:35|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 16:09:50 -04)" was missed by 0:00:45.060227|
2025-05-10 16:02:23|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-05-10 16:10:38|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 16:24:50 -04)" was missed by 0:00:48.620178|
2025-05-10 16:25:39|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 16:39:50 -04)" was missed by 0:00:49.069600|
2025-05-10 16:40:39|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 16:54:50 -04)" was missed by 0:00:49.476719|
2025-05-10 16:55:42|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 17:09:50 -04)" was missed by 0:00:52.600766|
2025-05-10 17:10:41|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 17:24:50 -04)" was missed by 0:00:51.583598|
2025-05-10 17:25:45|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 17:39:50 -04)" was missed by 0:00:54.963250|
2025-05-10 17:31:54|ERROR   |app.app                         |Exception on /images/movies/radarr/MediaCover/23/poster-500.jpg [GET]|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1463, in wsgi_app\n    response = self.full_dispatch_request()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 872, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 672, in error_router\n    return original_handler(e)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_cors/extension.py", line 176, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n                                                ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 855, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/app/ui.py", line 146, in movies_images\n    return Response(stream_with_context(req.iter_content(2048)), content_type=req.headers[\'content-type\'])\n                                                                              ~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/structures.py", line 52, in __getitem__\n    return self._store[key.lower()][1]\n           ~~~~~~~~~~~^^^^^^^^^^^^^\nKeyError: \'content-type\''|
2025-05-10 17:31:54|ERROR   |app.app                         |Exception on /images/movies/radarr/MediaCover/23/fanart.jpg [GET]|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1463, in wsgi_app\n    response = self.full_dispatch_request()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 872, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 672, in error_router\n    return original_handler(e)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_cors/extension.py", line 176, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n                                                ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 855, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/app/ui.py", line 146, in movies_images\n    return Response(stream_with_context(req.iter_content(2048)), content_type=req.headers[\'content-type\'])\n                                                                              ~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/structures.py", line 52, in __getitem__\n    return self._store[key.lower()][1]\n           ~~~~~~~~~~~^^^^^^^^^^^^^\nKeyError: \'content-type\''|
2025-05-10 17:34:04|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-05-10 17:34:14|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-05-10 17:34:28|ERROR   |app.app                         |Exception on /images/movies/radarr/MediaCover/23/poster-500.jpg [GET]|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1463, in wsgi_app\n    response = self.full_dispatch_request()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 872, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 672, in error_router\n    return original_handler(e)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_cors/extension.py", line 176, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n                                                ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 855, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/app/ui.py", line 146, in movies_images\n    return Response(stream_with_context(req.iter_content(2048)), content_type=req.headers[\'content-type\'])\n                                                                              ~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/structures.py", line 52, in __getitem__\n    return self._store[key.lower()][1]\n           ~~~~~~~~~~~^^^^^^^^^^^^^\nKeyError: \'content-type\''|
2025-05-10 17:34:29|ERROR   |app.app                         |Exception on /images/movies/radarr/MediaCover/23/fanart.jpg [GET]|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1463, in wsgi_app\n    response = self.full_dispatch_request()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 872, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 672, in error_router\n    return original_handler(e)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask_cors/extension.py", line 176, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n                                                ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 855, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/app/ui.py", line 146, in movies_images\n    return Response(stream_with_context(req.iter_content(2048)), content_type=req.headers[\'content-type\'])\n                                                                              ~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/structures.py", line 52, in __getitem__\n    return self._store[key.lower()][1]\n           ~~~~~~~~~~~^^^^^^^^^^^^^\nKeyError: \'content-type\''|
2025-05-10 17:36:49|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-10 17:40:46|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 17:54:50 -04)" was missed by 0:00:56.500425|
2025-05-10 17:50:14|WARNING |apscheduler.executors.default   |Run time of job "Update Release Info (trigger: interval[3:00:00], next run at: 2025-05-10 20:49:38 -04)" was missed by 0:00:36.530471|
2025-05-10 17:55:09|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 18:09:50 -04)" was missed by 0:00:19.471897|
2025-05-10 18:10:57|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 18:24:50 -04)" was missed by 0:01:07.167868|
2025-05-10 18:25:55|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 18:39:50 -04)" was missed by 0:01:05.537309|
2025-05-10 18:40:52|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 18:54:50 -04)" was missed by 0:01:01.817024|
2025-05-10 18:56:01|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 19:09:50 -04)" was missed by 0:01:11.156052|
2025-05-10 19:11:02|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 19:24:50 -04)" was missed by 0:01:12.177317|
2025-05-10 19:26:01|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 19:39:50 -04)" was missed by 0:01:11.450490|
2025-05-10 19:41:03|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 19:54:50 -04)" was missed by 0:01:13.517860|
2025-05-10 19:48:14|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-05-10 19:56:05|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 20:09:50 -04)" was missed by 0:01:15.104357|
2025-05-10 20:11:10|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 20:24:50 -04)" was missed by 0:01:20.617019|
2025-05-10 20:26:07|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 20:39:50 -04)" was missed by 0:01:16.959517|
2025-05-10 20:41:08|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 20:54:50 -04)" was missed by 0:01:18.360704|
2025-05-10 20:45:50|WARNING |apscheduler.executors.default   |Run time of job "Search for Missing Movies Subtitles (trigger: interval[6:00:00], next run at: 2025-05-11 02:45:27 -04)" was missed by 0:00:23.196892|
2025-05-10 20:47:08|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-05-10 20:55:17|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 21:09:50 -04)" was missed by 0:00:26.885784|
2025-05-10 20:59:19|WARNING |apscheduler.executors.default   |Run time of job "Update Announcements File (trigger: interval[6:00:00], next run at: 2025-05-11 02:58:55 -04)" was missed by 0:00:23.973855|
2025-05-10 21:05:45|WARNING |apscheduler.executors.default   |Run time of job "Check Health (trigger: interval[6:00:00], next run at: 2025-05-11 03:05:12 -04)" was missed by 0:00:33.566082|
2025-05-10 21:10:17|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 21:24:50 -04)" was missed by 0:00:27.558679|
2025-05-10 21:26:20|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 21:39:50 -04)" was missed by 0:01:30.573234|
2025-05-10 21:41:15|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 21:54:50 -04)" was missed by 0:01:25.571295|
2025-05-10 21:56:12|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 22:09:50 -04)" was missed by 0:01:22.630943|
2025-05-10 22:11:20|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 22:24:50 -04)" was missed by 0:01:29.810297|
2025-05-10 22:26:20|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 22:39:50 -04)" was missed by 0:01:30.056587|
2025-05-10 22:41:17|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 22:54:50 -04)" was missed by 0:01:26.798846|
2025-05-10 22:56:20|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 23:09:50 -04)" was missed by 0:01:30.057390|
