2025-05-09 00:38:42|ERROR   |root                            |BAZARR cannot bind to specified IP, trying with ***.***.***.***|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server\n    self.server = create_server(app,\n                  ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server\n    last_serv = TcpWSGIServer(\n                ^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__\n    self.bind_server_socket()\n  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket\n    self.bind(sockaddr)\n  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind\n    return self.socket.bind(addr)\n           ^^^^^^^^^^^^^^^^^^^^^^\nOSError: [Errno 99] Address not available'|
2025-05-09 00:38:45|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-05-09 00:38:45|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-05-09 00:38:45|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-05-09 00:38:46|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-05-09 00:38:47|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-05-09 00:49:28|INFO    |root                            |Using opensubtitlescom again after 6 hours, (disabled because: DownloadLimitExceeded)|
2025-05-09 01:07:58|ERROR   |root                            |BAZARR ffprobe cannot analyze this video file /tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E08.1080p.BluRay.x265-RARBG[eztv.re].mp4. Could it be corrupted? +-------------------------------------------------------+
|                     KnowIt 0.5.3                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         6.1.0                         |
|                   libmediainfo.so.0                   |
|                        v24.11                         |
|                                                       |
|                   /usr/bin/ffprobe                    |
|                        v6.1.2                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   provider: ffmpeg                    |
|               ffmpeg: /usr/bin/ffprobe                |
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 222, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 80, in extract_info
    json_dump = self._execute(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 114, in _execute
    return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E08.1080p.BluRay.x265-RARBG[eztv.re].mp4']' returned non-zero exit status 1.

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+|
2025-05-09 01:08:00|ERROR   |root                            |BAZARR ffprobe cannot analyze this video file /tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E08.1080p.BluRay.x265-RARBG[eztv.re].mp4. Could it be corrupted? +-------------------------------------------------------+
|                     KnowIt 0.5.3                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         6.1.0                         |
|                   libmediainfo.so.0                   |
|                        v24.11                         |
|                                                       |
|                   /usr/bin/ffprobe                    |
|                        v6.1.2                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   provider: ffmpeg                    |
|               ffmpeg: /usr/bin/ffprobe                |
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 222, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 80, in extract_info
    json_dump = self._execute(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 114, in _execute
    return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E08.1080p.BluRay.x265-RARBG[eztv.re].mp4']' returned non-zero exit status 1.

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+|
2025-05-09 01:08:03|ERROR   |root                            |BAZARR ffprobe cannot analyze this video file /tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E08.1080p.BluRay.x265-RARBG[eztv.re].mp4. Could it be corrupted? +-------------------------------------------------------+
|                     KnowIt 0.5.3                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         6.1.0                         |
|                   libmediainfo.so.0                   |
|                        v24.11                         |
|                                                       |
|                   /usr/bin/ffprobe                    |
|                        v6.1.2                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   provider: ffmpeg                    |
|               ffmpeg: /usr/bin/ffprobe                |
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 222, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 80, in extract_info
    json_dump = self._execute(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 114, in _execute
    return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E08.1080p.BluRay.x265-RARBG[eztv.re].mp4']' returned non-zero exit status 1.

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+|
2025-05-09 01:09:05|ERROR   |root                            |BAZARR ffprobe cannot analyze this video file /tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E10.1080p.BluRay.x265-RARBG[eztv.re].mp4. Could it be corrupted? +-------------------------------------------------------+
|                     KnowIt 0.5.3                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         6.1.0                         |
|                   libmediainfo.so.0                   |
|                        v24.11                         |
|                                                       |
|                   /usr/bin/ffprobe                    |
|                        v6.1.2                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   provider: ffmpeg                    |
|               ffmpeg: /usr/bin/ffprobe                |
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 222, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 80, in extract_info
    json_dump = self._execute(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 114, in _execute
    return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E10.1080p.BluRay.x265-RARBG[eztv.re].mp4']' returned non-zero exit status 1.

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+|
2025-05-09 01:09:05|ERROR   |root                            |BAZARR ffprobe cannot analyze this video file /tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E10.1080p.BluRay.x265-RARBG[eztv.re].mp4. Could it be corrupted? +-------------------------------------------------------+
|                     KnowIt 0.5.3                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         6.1.0                         |
|                   libmediainfo.so.0                   |
|                        v24.11                         |
|                                                       |
|                   /usr/bin/ffprobe                    |
|                        v6.1.2                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   provider: ffmpeg                    |
|               ffmpeg: /usr/bin/ffprobe                |
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 222, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 80, in extract_info
    json_dump = self._execute(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 114, in _execute
    return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/tv/House of the Dragon/Season 1/House.of.the.Dragon.S01E10.1080p.BluRay.x265-RARBG[eztv.re].mp4']' returned non-zero exit status 1.

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+|
2025-05-09 03:38:03|INFO    |root                            |Throttling opensubtitlescom for 6 hours, until 25/05/09 09:38, because of: DownloadLimitExceeded. Exception info: "'Daily download limit reached. 21 subtitles have been downloaded and -1 r' ~ opensubtitlescom.py@543"|
2025-05-09 03:53:16|ERROR   |root                            |BAZARR cannot get series returned by SignalR feed from Sonarr API.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.12/json/decoder.py", line 338, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.12/json/decoder.py", line 356, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/series.py", line 226, in update_one_series\n    series_data = get_series_from_sonarr_api(apikey_sonarr=settings.sonarr.apikey, sonarr_series_id=int(series_id))\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 95, in get_series_from_sonarr_api\n    result = r.json()\n             ^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nrequests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)'|
2025-05-09 04:00:18|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
2025-05-09 04:00:17|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
2025-05-09 06:13:57|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/Supernatural/Season 3/Supernatural S03E11 Mystery Spot  [1080p x265 10bit Joy].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 06:13:58|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/Supernatural/Season 3/Supernatural S03E12 Jus in Bello  [1080p x265 10bit Joy].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 06:13:58|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/Supernatural/Season 3/Supernatural S03E13 Ghostfacers  [1080p x265 10bit Joy].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 06:13:58|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/Supernatural/Season 3/Supernatural S03E14 Long Distance Call  [1080p x265 10bit Joy].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 06:13:58|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/Supernatural/Season 3/Supernatural S03E15 Time Is on My Side  [1080p x265 10bit Joy].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 06:13:58|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/Supernatural/Season 3/Supernatural S03E16 No Rest for the Wicked  [1080p x265 10bit Joy].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 06:14:34|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-05-09 06:25:57|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-09 07:53:16|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 08:07:57 -04)" was missed by 0:00:18.925095|
2025-05-09 08:08:18|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 08:22:57 -04)" was missed by 0:00:21.251451|
2025-05-09 08:23:21|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 08:37:57 -04)" was missed by 0:00:24.496871|
2025-05-09 08:38:16|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 08:52:57 -04)" was missed by 0:00:19.249032|
2025-05-09 08:53:26|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 09:07:57 -04)" was missed by 0:00:29.111847|
2025-05-09 09:08:28|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 09:22:57 -04)" was missed by 0:00:30.973529|
2025-05-09 09:23:31|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 09:37:57 -04)" was missed by 0:00:34.139677|
2025-05-09 09:38:13|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 09:52:57 -04)" was missed by 0:00:16.385918|
2025-05-09 09:46:20|WARNING |apscheduler.executors.default   |Run time of job "Upgrade Previously Downloaded Subtitles (trigger: interval[12:00:00], next run at: 2025-05-09 21:46:01 -04)" was missed by 0:00:19.326535|
2025-05-09 09:53:15|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 10:07:57 -04)" was missed by 0:00:18.021561|
2025-05-09 10:08:40|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 10:22:57 -04)" was missed by 0:00:42.606529|
2025-05-09 10:23:39|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 10:37:57 -04)" was missed by 0:00:42.129994|
2025-05-09 10:38:28|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 10:52:57 -04)" was missed by 0:00:31.413270|
2025-05-09 10:53:45|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 11:07:57 -04)" was missed by 0:00:48.537476|
2025-05-09 11:08:48|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 11:22:57 -04)" was missed by 0:00:50.779943|
2025-05-09 11:23:48|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 11:37:57 -04)" was missed by 0:00:50.794666|
2025-05-09 11:38:37|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 11:52:57 -04)" was missed by 0:00:39.916153|
2025-05-09 11:53:53|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 12:07:57 -04)" was missed by 0:00:56.364290|
2025-05-09 12:08:53|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 12:22:57 -04)" was missed by 0:00:56.193460|
2025-05-09 12:14:17|WARNING |apscheduler.executors.default   |Run time of job "Search for Missing Series Subtitles (trigger: interval[6:00:00], next run at: 2025-05-09 18:13:57 -04)" was missed by 0:00:20.466357|
2025-05-09 12:23:32|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 12:37:57 -04)" was missed by 0:00:35.536362|
2025-05-09 12:26:08|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-09 12:38:12|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 12:52:57 -04)" was missed by 0:00:15.144883|
2025-05-09 12:54:03|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 13:07:57 -04)" was missed by 0:01:05.687024|
2025-05-09 13:09:03|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 13:22:57 -04)" was missed by 0:01:05.803514|
2025-05-09 13:24:05|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 13:37:57 -04)" was missed by 0:01:07.868020|
2025-05-09 13:38:49|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 13:52:57 -04)" was missed by 0:00:52.192161|
2025-05-09 13:54:07|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 14:07:57 -04)" was missed by 0:01:10.303617|
2025-05-09 14:09:09|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 14:22:57 -04)" was missed by 0:01:12.498827|
2025-05-09 14:24:09|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 14:37:57 -04)" was missed by 0:01:11.549735|
2025-05-09 14:27:40|WARNING |apscheduler.executors.default   |Run time of job "Sync with Radarr (trigger: interval[1:00:00], next run at: 2025-05-09 15:27:21 -04)" was missed by 0:00:18.570985|
2025-05-09 14:38:52|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 14:52:57 -04)" was missed by 0:00:54.984088|
2025-05-09 14:54:15|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 15:07:57 -04)" was missed by 0:01:17.642919|
2025-05-09 15:09:12|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 15:22:57 -04)" was missed by 0:01:15.434456|
2025-05-09 15:24:09|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 15:37:57 -04)" was missed by 0:01:11.717085|
2025-05-09 15:25:51|INFO    |root                            |Successful authentication from ***.***.***.*** for user n30x|
2025-05-09 15:26:30|INFO    |root                            |Using opensubtitlescom again after 6 hours, (disabled because: DownloadLimitExceeded)|
2025-05-09 15:26:58|INFO    |root                            |Throttling opensubtitlescom for 6 hours, until 25/05/09 21:26, because of: DownloadLimitExceeded. Exception info: "'Daily download limit reached. 21 subtitles have been downloaded and -1 r' ~ opensubtitlescom.py@543"|
2025-05-09 15:30:25|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-05-09 15:31:56|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 198, in _new_conn\n    sock = connection.create_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 73, in create_connection\n    sock.connect(sa)\nTimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 793, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 491, in _make_request\n    raise new_e\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 467, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1099, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 616, in connect\n    self.sock = sock = self._new_conn()\n                       ^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 207, in _new_conn\n    raise ConnectTimeoutError(\nurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb485768890>, \'Connection to api.github.com timed out. (connect timeout=15)\')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 486, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 847, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb485768890>, \'Connection to api.github.com timed out. (connect timeout=15)\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 28, in check_releases\n    r = requests.get(url_releases, allow_redirects=True, timeout=15)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 507, in send\n    raise ConnectTimeout(e, request=request)\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb485768890>, \'Connection to api.github.com timed out. (connect timeout=15)\'))'|
2025-05-09 15:38:13|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 15:52:57 -04)" was missed by 0:00:15.797649|
2025-05-09 15:54:06|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 16:07:57 -04)" was missed by 0:01:09.456564|
2025-05-09 16:09:21|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 16:22:57 -04)" was missed by 0:01:24.204843|
2025-05-09 16:24:18|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 16:37:57 -04)" was missed by 0:01:21.136114|
2025-05-09 16:27:39|WARNING |apscheduler.executors.default   |Run time of job "Sync with Radarr (trigger: interval[1:00:00], next run at: 2025-05-09 17:27:21 -04)" was missed by 0:00:18.234569|
2025-05-09 16:38:59|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 16:52:57 -04)" was missed by 0:01:02.208792|
2025-05-09 16:54:26|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 17:07:57 -04)" was missed by 0:01:28.881887|
2025-05-09 17:09:15|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 17:22:57 -04)" was missed by 0:01:17.561971|
2025-05-09 17:24:22|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 17:37:57 -04)" was missed by 0:01:24.864877|
2025-05-09 17:27:40|WARNING |apscheduler.executors.default   |Run time of job "Sync with Radarr (trigger: interval[1:00:00], next run at: 2025-05-09 18:27:21 -04)" was missed by 0:00:19.360514|
2025-05-09 17:39:06|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 17:52:57 -04)" was missed by 0:01:09.350514|
2025-05-09 17:54:17|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 18:07:57 -04)" was missed by 0:01:20.158336|
2025-05-09 18:09:18|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 18:22:57 -04)" was missed by 0:01:20.785481|
2025-05-09 18:14:21|WARNING |apscheduler.executors.default   |Run time of job "Search for Missing Series Subtitles (trigger: interval[6:00:00], next run at: 2025-05-10 00:13:57 -04)" was missed by 0:00:24.515740|
2025-05-09 18:23:49|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 18:37:57 -04)" was missed by 0:00:52.125147|
2025-05-09 18:26:12|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-09 18:34:59|WARNING |apscheduler.executors.default   |Run time of job "Update Announcements File (trigger: interval[6:00:00], next run at: 2025-05-10 00:34:40 -04)" was missed by 0:00:18.937401|
2025-05-09 18:38:17|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 18:52:57 -04)" was missed by 0:00:19.694650|
2025-05-09 18:54:34|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 19:07:57 -04)" was missed by 0:01:36.642169|
2025-05-09 19:09:22|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 19:22:57 -04)" was missed by 0:01:25.211800|
2025-05-09 19:23:28|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-05-09 19:23:35|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-05-09 19:23:35|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 19:37:57 -04)" was missed by 0:00:38.238065|
2025-05-09 19:23:38|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-05-09 19:23:47|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-05-09 21:24:16|INFO    |root                            |Successful authentication from ***.***.***.*** for user n30x|
2025-05-09 21:27:18|INFO    |root                            |Using opensubtitlescom again after 6 hours, (disabled because: DownloadLimitExceeded)|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 01 [BDRip 1920x1080 x265 10bit FLAC] [DA6CE52F].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 02 [BDRip 1920x1080 x265 10bit FLAC] [3AA03292].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 03 [BDRip 1920x1080 x265 10bit FLAC] [D684043D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 04 [BDRip 1920x1080 x265 10bit FLAC] [B2C4B260].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken OAD 05 [BDRip 1920x1080 x265 10bit FLAC] [A61CD70F].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 06 [BDRip 1920x1080 x265 10bit FLAC] [0C4CF4F1].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 07 [BDRip 1920x1080 x265 10bit FLAC] [D64A1B81].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 08 [BDRip 1920x1080 x265 10bit FLAC] [95CC9BDE].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 09 [BDRip 1920x1080 x265 10bit FLAC] [BADBFE7D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 10 [BDRip 1920x1080 x265 10bit FLAC] [0DEA73A4].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 11 [BDRip 1920x1080 x265 10bit FLAC] [4AC2993B].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:19|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 12 [BDRip 1920x1080 x265 10bit FLAC] [77C7703D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 13 [BDRip 1920x1080 x265 10bit FLAC] [5460A656].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 14 [BDRip 1920x1080 x265 10bit FLAC] [FB988851].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 15 [BDRip 1920x1080 x265 10bit FLAC] [A4CE7240].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 16 [BDRip 1920x1080 x265 10bit FLAC] [5E296D73].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 17 [BDRip 1920x1080 x265 10bit FLAC] [38624123].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 18 [BDRip 1920x1080 x265 10bit FLAC] [F52D68F5].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 19 [BDRip 1920x1080 x265 10bit FLAC] [3C151DE6].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 20 [BDRip 1920x1080 x265 10bit FLAC] [0FA23A05].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 21 [BDRip 1920x1080 x265 10bit FLAC] [06E58E6A].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 22 [BDRip 1920x1080 x265 10bit FLAC] [392E95B1].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 23 [BDRip 1920x1080 x265 10bit FLAC] [7B47C819].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 1/[Asakura] Tensei Shitara Slime Datta Ken 24 [BDRip 1920x1080 x265 10bit FLAC] [920274ED].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:20|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 28 [BDRip 1920x1080 x265 10bit FLAC] [3FE7BEE0].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 29 [BDRip 1920x1080 x265 10bit FLAC] [56305A3D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 30 [BDRip 1920x1080 x265 10bit FLAC] [F4DEFA89].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 31 [BDRip 1920x1080 x265 10bit FLAC] [7B6E7D26].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 32 [BDRip 1920x1080 x265 10bit FLAC] [85DFB5EC].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 33 [BDRip 1920x1080 x265 10bit FLAC] [79959F0D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 34 [BDRip 1920x1080 x265 10bit FLAC] [B2510CD1].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 35 [BDRip 1920x1080 x265 10bit FLAC] [D7670DD6].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 36 [BDRip 1920x1080 x265 10bit FLAC] [F8D09D93].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 37 [BDRip 1920x1080 x265 10bit FLAC] [D54C267E].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 38 [BDRip 1920x1080 x265 10bit FLAC] [975B5E8A].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 39 [BDRip 1920x1080 x265 10bit FLAC] [6F33AB5D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 40 [BDRip 1920x1080 x265 10bit FLAC] [6F79B61E].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 41 [BDRip 1920x1080 x265 10bit FLAC] [6F0627A1].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:21|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 42 [BDRip 1920x1080 x265 10bit FLAC] [D921ECD6].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 43 [BDRip 1920x1080 x265 10bit FLAC] [46106DDA].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 44 [BDRip 1920x1080 x265 10bit FLAC] [51B1E792].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 45 [BDRip 1920x1080 x265 10bit FLAC] [6D4D6FE2].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 46 [BDRip 1920x1080 x265 10bit FLAC] [3D921568].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 47 [BDRip 1920x1080 x265 10bit FLAC] [A4F61EE2].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 2/[Asakura] Tensei Shitara Slime Datta Ken 2nd Season 48 [BDRip 1920x1080 x265 10bit FLAC] [E1C9F618].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 49 [BDRip 1920x1080 x265 10bit FLAC] [36E425AB].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 50 [BDRip 1920x1080 x265 10bit FLAC] [000863F8].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 51 [BDRip 1920x1080 x265 10bit FLAC] [B1DA138C].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 52 [BDRip 1920x1080 x265 10bit FLAC] [57CC77D1].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 53 [BDRip 1920x1080 x265 10bit FLAC] [E54E136D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 54 [BDRip 1920x1080 x265 10bit FLAC] [9AD8661E].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:22|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 55 [BDRip 1920x1080 x265 10bit FLAC] [CA1987F4].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 56 [BDRip 1920x1080 x265 10bit FLAC] [6A06D86C].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 57 [BDRip 1920x1080 x265 10bit FLAC] [8DEDFBFC].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 58 [BDRip 1920x1080 x265 10bit FLAC] [3128A4C1].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 59 [BDRip 1920x1080 x265 10bit FLAC] [FEF3C14B].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 60 [BDRip 1920x1080 x265 10bit FLAC] [E13F246D].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 61 [BDRip 1920x1080 x265 10bit FLAC] [0646FB1A].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 62 [BDRip 1920x1080 x265 10bit FLAC] [B69B4886].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 63 [BDRip 1920x1080 x265 10bit FLAC] [276E23F3].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 64 [BDRip 1920x1080 x265 10bit FLAC] [35F89881].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 65 [BDRip 1920x1080 x265 10bit FLAC] [49BF2267].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 66 [BDRip 1920x1080 x265 10bit FLAC] [51655149].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:23|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 67 [BDRip 1920x1080 x265 10bit FLAC] [A10616B4].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:24|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 68 [BDRip 1920x1080 x265 10bit FLAC] [F84ADF72].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:24|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 69 [BDRip 1920x1080 x265 10bit FLAC] [F15B8F67].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:24|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 70 [BDRip 1920x1080 x265 10bit FLAC] [02A1D871].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:24|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 71 [BDRip 1920x1080 x265 10bit FLAC] [85468408].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:24|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Season 3/[Asakura] Tensei Shitara Slime Datta Ken 3rd Season 72 [BDRip 1920x1080 x265 10bit FLAC] [0782E4DD].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:24|ERROR   |root                            |BAZARR Error (Path does not exist) trying to get video information for this file: /tv/That Time I Got Reincarnated as a Slime/Specials/[Yameii] That Time I Got Reincarnated as a Slime - S00E14 [English Dub] [CR WEB-DL 1080p] [431367FB].mkv|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 35, in get_video\n    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 839, in scan_video\n    raise ValueError(\'Path does not exist\')\nValueError: Path does not exist'|
2025-05-09 21:27:24|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
2025-05-09 21:32:20|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
2025-05-09 21:32:53|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-09 21:32:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-09 21:32:56|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2025-05-09 21:33:14|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
2025-05-09 21:46:17|WARNING |apscheduler.executors.default   |Run time of job "Upgrade Previously Downloaded Subtitles (trigger: interval[12:00:00], next run at: 2025-05-10 09:46:01 -04)" was missed by 0:00:16.453960|
2025-05-09 21:48:30|INFO    |root                            |BAZARR Running cache maintenance|
2025-05-09 22:04:02|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 22:18:38 -04)" was missed by 0:00:23.709530|
2025-05-09 22:19:04|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 22:33:38 -04)" was missed by 0:00:25.572515|
2025-05-09 22:32:54|WARNING |apscheduler.executors.default   |Run time of job "Sync with Radarr (trigger: interval[1:00:00], next run at: 2025-05-09 23:32:28 -04)" was missed by 0:00:26.684041|
2025-05-09 22:44:24|INFO    |root                            |Successful authentication from ***.***.***.*** for user n30x|
2025-05-09 22:49:08|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 23:03:38 -04)" was missed by 0:00:29.946171|
2025-05-09 23:04:09|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 23:18:38 -04)" was missed by 0:00:30.502341|
2025-05-09 23:19:13|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-09 23:33:38 -04)" was missed by 0:00:34.940678|
2025-05-09 23:33:01|WARNING |apscheduler.executors.default   |Run time of job "Sync with Radarr (trigger: interval[1:00:00], next run at: 2025-05-10 00:32:28 -04)" was missed by 0:00:33.437118|
2025-05-09 23:49:19|WARNING |apscheduler.executors.default   |Run time of job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2025-05-10 00:03:38 -04)" was missed by 0:00:40.702356|
